### ISSUE TITLE
Problem accessing meshcentral 0.5.1-k via safari on iPhone 

### ISSUE THREAD

**Issue by tradexsrl** [Ylianst/MeshCentral#1139]
Hi today I’m trying to access meshcentral via my iPhone 11pro iOS 13.4.1 and I can only see this page after mfa login
![MeshCentral](https://user-images.githubusercontent.com/62424179/79008769-63d0ec00-7b5e-11ea-9f81-ca62368a3a5a.png)

**Comment by tradexsrl** [comment]
the same on latest firefox for ios , even when asking for desktop version of the website...

**Comment by olivier37520** [comment]
I never succeed access meshcentral from iPhone. I tryed safari, Firefox, chrome, opera, dolphin and a lot of web browser for the same result, blank page. I’ve planned to debug in a simulator to help.

**Comment by Ylianst** [comment]
One thing I noticed about Safari is that if you don't have a real TLS certificate on your server, the Safari browser will refuse to do a WebSocket connection to the server. If you try [https://meshcentral.com](https://meshcentral.com), it works for me on my iPad, but without a valid Let's Encrypt certificate, I can't connect and I am not sure I can do anything to fix it. It looks like a Safari bug.

What certificate are you using on your server? - Thanks.

**Comment by olivier37520** [comment]
I’m using a valid let’s encrypt certificate but behind nginx proxy managed by Debian plesk (ovh os image)

**Comment by Ylianst** [comment]
Weird, my servers seems to work, if you can test https://meshcentral.com, you don't need to add a device, just create an account a login. If that works, you can try sending me a dummy account on your server so I can investigate, [my contact info is here](https://www.meshcommander.com/contact-information).

**Comment by olivier37520** [comment]
I started debug, and found a security error on ws connect. 
Operation insecure, refused to connect to wss://xxx.xxx.xxx/control.ashx because it does not appear in the connect-src directive of the Content Security Policy
See in CSP header wss://127.0.0.1:4430 instead dns of the server. This should be fixed by configuration but can’t find where

**Comment by olivier37520** [comment]
I forgot 
`proxy_set_header Host $host;`
In my nginx conf to keep original host request. Works now but admin account seems to have restricted access ( no users nor server tab)

**Comment by tradexsrl** [comment]
i have tested my iphone with your meshcentral and it works but after some seconds it appear "server disconnected.click here to reconnect" ...if i click on reconnect it does reconnect correctly...my MC doesn't have any certificate except the one auto generated at software install but in safari you can go at the bottom of the page and force to continue to that page. i have done this on two our internal services that has no https and the login process works as usual...

**Comment by si458** [comment]
please use the latest version 1.1.20, reopen if still happening
