### ISSUE TITLE
Problem with Mesh Agent in Win XP and Win 7

### ISSUE THREAD

**Issue by dagors** [Ylianst/MeshCentral#18]
Just perform a MeshCentral 2 installation on a vps, everything works fine with windows 10 computers.
But I have the need to add 3 computers with windows 7 and 1 with windows XP.

On computers with windows 7 the installation is apparently complete but the device is not added in the mesh view, even the service is running but it does not work.
When you open the mesh agent installer again in Current Agent Status it is displayed as Not Installed.
Test only with the Connect option but it did not work either.

In Windows XP when trying to run MeshAgent the system presents a message: "This application is not compatible with the 32 Bit system" and the downloaded MeshAgent is the corresponding 32 bits.

**Comment by Ylianst** [comment]
Thanks for the report, Windows7 should work so I will give it a try and see what is going on. As for WinXP, right now there is no plan to support it because it lacks some of the features we use in the agent.

**Comment by nicrame** [comment]
> 
> 
> Just perform a MeshCentral 2 installation on a vps, everything works fine with windows 10 computers.
> But I have the need to add 3 computers with windows 7 and 1 with windows XP.
> 
> On computers with windows 7 the installation is apparently complete but the device is not added in the mesh view, even the service is running but it does not work.
> When you open the mesh agent installer again in Current Agent Status it is displayed as Not Installed.
> Test only with the Connect option but it did not work either.
> 
> In Windows XP when trying to run MeshAgent the system presents a message: "This application is not compatible with the 32 Bit system" and the downloaded MeshAgent is the corresponding 32 bits.

Did You try to start MeshAgent installer as Administrator (right mouse button, and chose run as administrator from menu)?

**Comment by Ylianst** [comment]
FYI. Just published MeshCentral 0.2.0-u on NPM with a critical bug fix for Windows7. If a agent is not acting right, update the server and delete "meshagent.db" on the computer and start the agent again. Should fix it.

**Comment by dagors** [comment]
@nicrame  Yes, I tried to do it by running as administrator but it did not work.



> FYI. Just published MeshCentral 0.2.0-u on NPM with a critical bug fix for Windows7. If a agent is not acting right, update the server and delete "meshagent.db" on the computer and start the agent again. Should fix it.

I already made the update of the server to the latest version, on a computer I was able to complete the installation and everything works.
In another still does not work, when I install everything normal but does not create the .db and .sh files.
When trying to connect only if it generates the files but the device does not appear in the account.
Try running as administrator did not work.
Check windows firewall rules, antivirus and everything is fine.

**Comment by Ylianst** [comment]
One way to debug the agent on Windows is to open a command prompt and run "meshagent.exe run". This will run the agent is the command line and it will show what it is doing. Hopefully it will be obvious what the problem is.

**Comment by dagors** [comment]
Perform the procedure:
In win 7
C: \ Users \ admin \ Downloads> meshagent.exe run
MeshCentral2 Agent
Generating Certificates ...
Connecting to: wss: //remote.mydomine.com: 443 / agent.ashx

With Firewall off and without antivirus, I can ping to the server where meshcentral2 is installed.

In win 10
C: \ Users \ admin \ Downloads> meshagent.exe run
MeshCentral2 Agent
Generating Certificates ...
Connecting to: wss: //remote.mydomine.com: 443 / agent.ashx
Connected.

**Comment by Ylianst** [comment]
MeshAgent Windows7 support has been fixed a while back. If you see this issue again, please re-open or open a new issue. Also, no plan for WinXP support.

**Comment by adonaiechad** [comment]
Estimado, 
Tengo en un KVM un Windows Server 2012 R2  virtualizado y un windows 7, en ambos el agente de Mesh esta en ejecucion pero solo funciona en la WS2012, la vm de W7 tiene el servicio de mesh en ejecucion y no funciona no logro tomar desde meshcentral el equipo de hecho ni figura, actualice a ultima version MeshCentral v0.3.1-h que puedo probar no tengo ningun log. saludos GRACIAS

**Comment by adonaiechad** [comment]
Estimado, 
Tengo en un KVM un Windows Server 2012 R2  virtualizado y un windows 7, en ambos el agente de Mesh esta en ejecucion pero solo funciona en la WS2012, la vm de W7 tiene el servicio de mesh en ejecucion y no funciona no logro tomar desde meshcentral el equipo de hecho ni figura, actualice a ultima version MeshCentral v0.3.1-h que puedo probar no tengo ningun log. saludos GRACIAS
