### ISSUE TITLE
iOS web socket connection fail

### ISSUE THREAD

**Issue by I2700I** [Ylianst/MeshCentral#2025]
Unable to connect web socket, click to reconnect.
Server version: 0.7.6
Mobile devices: iPhone 11 Pro Max, iPad Air, iOS 14.2
Browsers used: Safari, Firefox, Chrome

**Comment by Ylianst** [comment]
A few things about iOS/Safari devices. 

- I have noticed that if you are using a un-trusted TLS certificate on your server, iOS devices will not connect. Even if you accept the invalid certificate, it will show the web site but refuse to connect the web socket and there is nothing you can do that I know of except to use Let's Encrypt and get a real TLS cert. You can test on [https://meshcentral.com](https://meshcentral.com) which should work.
- All iOS browsers are required to use the webkey engine, so it does not matter what browser you use.
- Yesterday I fixed a Safari issue if you are using a reverse-proxy on your server. If this is the case for you, let me know.

Hope that helps,
Ylian

**Comment by I2700I** [comment]
Got it. Set up a test server and didn't fix the certificate issue yet, will be addressed on moving to prod.
