### ISSUE TITLE
v0.7.33 - Unable to access desktop (remote control) of any clients

### ISSUE THREAD

**Issue by GRIFFCOMMca** [Ylianst/MeshCentral#2128]
Hi, posted this on the wrong github last night.....

- Windows 7 install (EXE installer used orginally)
- Apache port 443 as a front end proxy
- Last used and working 28 Dec with no issues, no Windows updates or Apache updates since then
- Able to log in and see clients, unable to remotely connect to any clients (both LAN and remote), only has TABS General, Events and Details when looking at each client).

Hi, this was working 28 Dec with no issues (i expect an older version than v0.7.33 which its on now as our server updates daily).

Not sure when this update happened as my server as it updates every day, but today i cant access ANY desktops from any clients (both LAN and remote). They are logging in, can only see General, Events and Details tabs for every client. Cant tell you the version of client as its not listed.

Has this broken in an update? we are running it behind an Apache web server port 443, last use3d 28 Dec with no issues, no updates to Apache or Windows.

Cant seem to find where to get the MeshAgent either, has that moved (appears to only be in the MAIN group of each area now)?
Also cant seem to find how to delete PCs in the console, so what ever this MESH version update was, its not good, please advise

**Comment by GRIFFCOMMca** [comment]
UPDATE
We just managed to gain access to remote control by logging in as the "original" global admin account, now remote control works.  The user i have (which is listed as an administrator) doesnt seem to have any access, so looks like the user tables went weird, it says i have access to 10 groups, on then selecting that user no groups are actually listed.

We are using Windows so looks like a user table issue from what i can see (any groups created by the "other" administrator account we created, cant be seen by the Global "original" administrator

**Comment by PathfinderNetworks** [comment]
Are you using MongoDB by any chance?

**Comment by GRIFFCOMMca** [comment]
No idea, it was the full windows install  i used (EXE install), how would i check this on the server?

I found the source of the issue, it appears the user permissions are screwed, when i log in as the original global administrator (admin) i can access the remote desktops, when i then check the user permissions they show as "Full Rights" on groups however on checking the permission check boxes, nothing is checked, if i then re-check "Full administrator" then save, and log in as that user the remote desktop works.

So its not showing the some tabs as its not reading the permissions for each user correctly (for what ever reason).

**Comment by PathfinderNetworks** [comment]
If you use the Windows installer then you are running NeDB for the database- as that's the default.  To run MongoDB you have to manually install Mongo and make some configuration changes for MeshCentral to use it.
Odd that you are seeing this similar permissions issue on NeDB.  You are correct, something is corrupting the permissions.  It's happening for me when I try to migrate from NeDB to MongoDB (hence why I asked if that's what you were using).

**Comment by GRIFFCOMMca** [comment]
Glad you have managed to nailed own the issue, it means a fix will be soon.

**Comment by Ylianst** [comment]
Hi. If the problem that it will not connect, or that the "Desktop" tab is missing? If the tab is missing, click on a device, go to the "Console" tab. Hit "Agent Action" and select "Upload default server core" and click ok. Let me know if the tabs come back.

![image](https://user-images.githubusercontent.com/1319013/103388130-4103b080-4abc-11eb-8178-97ee76295f54.png)

If this is not the problem, also let me know.

**Comment by LPJon** [comment]
Not the issue. You are not able to get to the "Console" tab in order to upload the default core. This tab is missing but the agent reports connected.

**Comment by Ylianst** [comment]
Ok. Just published MeshCentral v0.7.34 that does not mess up the database. Looking into the root cause now.

**Comment by Ylianst** [comment]
Ok. I have a working theory as to what is going on. The problem will only occur for accounts with a dot (.) the name. So, accounts the email addresses as the name, etc. These accounts need special escaping since MongoDB and NeDB don't allow a dot in the field name.

This is also good because I can work on reversing the issue, so a server update will fix it.

**Comment by Ylianst** [comment]
Working on a fix, will take a few hours to validate.

**Comment by LPJon** [comment]
That's awesome! I can confirm that the affected account username was an email address and that same account was used for the update. I can also confirm that the original admin account was not and email address and was used to workaround this issue by reassigning permissions to user-groups and device-groups. So your working theory seems to hold true. Can't wait for the update.

Also! Great response time! I'm extremely impressed keep up the great work! This is a great project!

**Comment by GRIFFCOMMca** [comment]
> Ok. I have a working theory as to what is going on. The problem will only occur for accounts with any of these 3 special chars: dot (.), dollar ($) and parentage (%) in the name. So, accounts with an email addresses as the name, etc. These accounts need special escaping since MongoDB and NeDB don't allow a dot in the field name.
> 
> This is also good because I can work on reversing the issue, so a server update will fix it.

We use firname.lastname in all usernames ....  version 0.7.34 still has the same fault (i left one user alone to know if it was fixed)

**Comment by Ylianst** [comment]
Version 0.7.34 will not create the problem if you update to it from an earlier version. If you now have the problem, hold on. I will a fix for it coming.

**Comment by GRIFFCOMMca** [comment]
> Version 0.7.34 will not create the problem if you update to it from an earlier version. If you now have the problem, hold on. I will have fix for it coming.

Cool, thanks

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.35, that should fix it. Let me know if it works.

**Comment by Ylianst** [comment]
Just patched MeshCentral.com to v0.7.35 since it must have had the same issue.

**Comment by LPJon** [comment]
I can confirm that upgrade from 0.7.32 to 0.7.35 works. Will report shortly with 0.7.33 to 0.7.35 results.

**Comment by LPJon** [comment]
I can also confirm that upgrading from 0.7.33(with confirmed permission issue) to 0.7.35 corrects this issue. It work!....thank you Sir.

**Comment by GRIFFCOMMca** [comment]
> > Ok. I have a working theory as to what is going on. The problem will only occur for accounts with any of these 3 special chars: dot (.), dollar ($) and parentage (%) in the name. So, accounts with an email addresses as the name, etc. These accounts need special escaping since MongoDB and NeDB don't allow a dot in the field name.
> > This is also good because I can work on reversing the issue, so a server update will fix it.
> 
> We use firname.lastname in all usernames .... version 0.7.34 still has the same fault (i left one user alone to know if it was fixed)

0.7.35 has not fixed the permissions issue (able to login, but still does not inherit the correct permissions, shows as text but nothing in the check boxes

**Comment by LPJon** [comment]
@GRIFFCOMMca Was your last upgrade from 0.7.34 to 0.7.35?

**Comment by Ylianst** [comment]
Same question, can you confirm you are on v0.7.35?

**Comment by GRIFFCOMMca** [comment]
Hi

Windows EXE installed originally (installed few years ago), had v0.7.33 (turns out was broken permissions), then upgraded to v0.7.34, problem not fixed, then on to v0.7.35, still not fixed, server says its on version 0.7.35

**Comment by PathfinderNetworks** [comment]
> Ok. I have a working theory as to what is going on. The problem will only occur for accounts with any of these 3 special chars: dot (.), dollar ($) and parentage (%) in the name. So, accounts with an email addresses as the name, etc. These accounts need special escaping since MongoDB and NeDB don't allow a dot in the field name.
> 
> This is also good because I can work on reversing the issue, so a server update will fix it.

This is exactly the trouble I am having with migrating to MongoDB then.  My username has a $ in it.

**Comment by Ylianst** [comment]
@GRIFFCOMMca When you click on a device, can you access the "console" tab? If you type "help" in the agent console, do you see a response? Can you do "Update default server core" like I suggested above?

**Comment by Ylianst** [comment]
@PathfinderNetworks Yes, hopefully your issue is now solved.

**Comment by GRIFFCOMMca** [comment]
> @GRIFFCOMMca When you click on a device, can you access the "console" tab? If you type "help" in the agent console, do you see a response? Can you do "Update default server core" like I suggested above?

If i log in as an "affected" user, no i dont see a tab CONSOLE, only General, Events and Details.  However this is a simple permissions issue, of which i will have fixed now as i only had a few users anyway to  update.

**Comment by Ylianst** [comment]
Ok. I just found another situation. Working on it.

**Comment by Ylianst** [comment]
Ha. I found that the fix in MeshCentral v0.7.35 in not being applied in a specific case. Will have an update shortly. This is impacting the users on meshcentral.com... so lucky for everyone, I see the problem.

**Comment by Ylianst** [comment]
MeshCentral v0.7.36 is out! That should work. If this server did not have any user groups at all, it would not apply the fix in v0.7.35. That is now solved. Let me know if that works.

**Comment by GRIFFCOMMca** [comment]
> MeshCentral v0.7.36 is out! That should work. If this server did not have any user groups at all, it would not apply the fix in v0.7.35. That is now solved. Let me know if that works.

We have installed it, no idea if it fixed the issue, as we manually fixed the permissions issues a few hours ago while on v0.7.35

**Comment by Ylianst** [comment]
Ok. Closing this since I had the same problem on MeshCentral.com, v0.7.35 did not fix it, but v0.7.36 fixed it. Please open a new issue if you see a problem.
