### ISSUE TITLE
Agent being blocked by User Account Control

### ISSUE THREAD

**Issue by Rafaeltck** [Ylianst/MeshCentral#251]
Hi, on the new Windows 10 May 2019 Update or 1903, build 18362.116, the mesh agent installation is being blocked by UAC. I already tested on some machines, if they are upgraded from 1809 the agent works just fine, but if i remove and try to install again or with a clean Windows 1903, the following UAC message is shown.

![Annotation 2019-05-28 174838](https://user-images.githubusercontent.com/5831537/58511547-6a868880-8171-11e9-85a2-abb8f3d332d0.png)

**Comment by PathfinderNetworks** [comment]
This is bad!  I just confirmed this on a new Windows 10 1903 PC that is here in my office.  Even though you choose the 'Run Anyway' option it still blocks the install with the message shown above.  And this is being run from an account with full local admin privileges.

**Comment by PathfinderNetworks** [comment]
I'm certain this is what is causing the issue.  Looks like 10 is no longer going to allow you to install apps that don't have certificates signed by a global authority.  No idea how we'd get around this now?
https://support.microsoft.com/en-us/help/3082125/uac-blocks-the-elevation-of-executable-applications-that-are-signed-wi

**Comment by wcrlewis** [comment]
This issue appeared tonight with two installations.  One uses McAfee and one has Symantec Endpoint SBE.  Each are Win10 Home x64 1809.

**Comment by wcrlewis** [comment]
> I'm certain this is what is causing the issue. Looks like 10 is no longer going to allow you to install apps that don't have certificates signed by a global authority. No idea how we'd get around this now other than Ylian signing the agents with a certificate from Intel or some other trusted source?
> https://support.microsoft.com/en-us/help/3082125/uac-blocks-the-elevation-of-executable-applications-that-are-signed-wi

I do not believe this is the issue.  It is difficult to believe MeshAgent's certificate was revoked.  I would agree the certificate may in some form be the issue.

**Comment by PathfinderNetworks** [comment]
> > I'm certain this is what is causing the issue. Looks like 10 is no longer going to allow you to install apps that don't have certificates signed by a global authority. No idea how we'd get around this now other than Ylian signing the agents with a certificate from Intel or some other trusted source?
> > https://support.microsoft.com/en-us/help/3082125/uac-blocks-the-elevation-of-executable-applications-that-are-signed-wi
> 
> I do not believe this is the issue. It is difficult to believe MeshAgent's certificate was revoked. I would agree the certificate may in some form be the issue.

 The certificate isn't revoked- it's just not signed by a trusted authority.  It's a self signed certificate that Ylian has created.  Microsoft is blocking self-signed certificates in addition to those that have been revoked.  Basically they are blocking any installer that is not signed with valid certificates.

**Comment by Ylianst** [comment]
Arg. Thanks for noticing this. I just looked and my certificate does seem to have been revoked. It was signed by a trusted root. I am looking into it now.

**Comment by Ylianst** [comment]
This [could be the problem](https://securityaffairs.co/wordpress/86153/malware/sectigo-certificates-chronicles-report.html). I and many others used [TotalVirus.com](www.virustotal.com) to check if the MeshAgent would pass a virus scan and the 32bit version did not. I imagine that two days ago a report was made that the MeshAgent was signed by my certificate and so, it got revoked. I contacted Sectigo support about this, hopefully I will get a response.

**Comment by wcrlewis** [comment]
Opening the agent from an admin powershell prompt (cd c:\users\xxx\downloads\|./MeshAgent_x64_Remote_Support.exe) and installing succeeds.

**Comment by Ylianst** [comment]
Because the Authenticode certificate is new revoked, I can't really use it anymore. I may still work on some computers, but in general it's not something I can use to sign. I will likely release a new version of MeshCentral tomorrow without code signing. If I get a new certificate, I will only be able to use it to sign software that passes the TotalVirus test.

**Comment by Ylianst** [comment]
One more finding, my certificate is in fact on this [list](https://gist.github.com/Blevene/6455fd7a898425d0546206d4be61fc68) from TotalVirus.

**Comment by Ylianst** [comment]
Released MeshCentral v0.3.5-m with self-signed MeshAgent, MeshCMD and MeshCentral Router. In the /node_modules/meshcentral/agents folder, there is a "codesign.cer" which is the public portion of the certificate used to sign the agent. Someone could install it as a trusted certificate if they want to get rid of the warning. Obviously, it's not ideal.

**Comment by PathfinderNetworks** [comment]
Thanks Ylian.  Will you, eventually, be signing it with a trusted Authenticode certificate down the road?

**Comment by wcrlewis** [comment]
Can we start a 'purchase a certificate' gofundme?

**Comment by Ylianst** [comment]
You guys are too nice. No need to do that, not about the money. The main problem is that if I get a new certificate, I can't use it to sign any binaries that don't pass the "totalvirus.com" test. I wish I would have known about this before hand. There is also the risk that the MeshAgent would be miss used.

One option would be to make it easy for for people deploying the MeshCentral server to sign their own agent, but we would have to make it so that a signed agent in this way could only connect to a specific server.

In any case, I opened a ticket with Comodo/Sectigo and they have not gotten back to me yet. Hopefully they will answer.

**Comment by D4V3M0NK** [comment]
Ylian,
We really do appreciate it's not about the money, but when someone takes on a project like this and keeps it regularly updated and responsive to its' users, then you can't imagine the relief that we feel. Therefore, I - for one - would welcome an ability to be able to show an appreciation towards the work you and your team put in. So, I've already reacted to @wcrlewis' post and I would expect others would do likewise. Therefore, please do reconsider.

**Comment by Ylianst** [comment]
You guys are just amazing, thank you. I am not going to take any money, however there is something that can help. I work for Intel and customer feedback is really important to us. If you guys can take a moment to write why you use MeshCentral, why you or your users like it, why you think it's going in the right direction, what I and team do well and where you would want it to go in the future... I would love to send this feedback to my management. You can post it publically, or send me an email privately at ylian.saint-hilaire at intel.com. I will most certainly forward it up the chain and would be super grateful.

**Comment by merlinweb** [comment]
Done ! Just a small step, hoping I can help in better way...

**Comment by Ylianst** [comment]
Someone else had the same thing happen and it went on [the main page of Slashdot](https://it.slashdot.org/story/19/06/02/0042209/ask-slashdot-what-to-do-when-your-certificate-authority-suddenly-revokes-your-cert).

**Comment by Ylianst** [comment]
FYI. Published MeshCentral v0.3.5-x that auto-updates all agents to the self-signed version. The past few versions had a self-signed agent but did not perform auto-update.

**Comment by plavirudar** [comment]
Is it possible to update the certificate on the Windows installer binary? 

The binary downloaded from the homepage https://www.meshcommander.com/meshcentral2 (specifically http://www.google.com/url?q=http%3A%2F%2Finfo.meshcentral.com%2Fdownloads%2FMeshCentral2%2FMeshCentralInstaller-1.6.exe&sa=D&sntz=1&usg=AFQjCNFBLcSemlflW5zQFeQNHOLuXc3PcQ) does not run due to the revoked certificate.

**Comment by Ylianst** [comment]
Thanks for pointing that out! I just fixed it.

**Comment by plavirudar** [comment]
> 
> 
> I'm certain this is what is causing the issue. Looks like 10 is no longer going to allow you to install apps that don't have certificates signed by a global authority. No idea how we'd get around this now other than Ylian signing the agents with a certificate from Intel or some other trusted source?

I don't believe that is currently the case. The apps are only blocked when they are signed with a revoked key, not when they are unsigned. An unsigned app (as is the case right now, since Comodo has not fixed the falsely revoked signing key) can still be run after manually allowing the install.

**Comment by Ylianst** [comment]
Quick update: Sectigo sent me an email saying my trouble ticket was escalated. Hopefully we will get a happy resolution.

**Comment by wcrlewis** [comment]
![image](https://user-images.githubusercontent.com/2782620/59617374-d82c3180-90eb-11e9-9f05-9c645d497999.png)

**Comment by Ylianst** [comment]
What version of the server is this? Starting with MeshCentral v0.3.6-m, this should be fixed.

**Comment by wcrlewis** [comment]
Downloaded 6/3 at 6PM CDT from meshcentral.com.  That is the best I can tell you right now.  It would be easier to know which version if the files' version tag was updated or some other marker was made.  Thank you for everything.

**Comment by Ylianst** [comment]
Yes, this certainly an early agent. You can right click on the executable, hit "properties" and look at the "Digital Signatures" tab. The current timestamp is June 14th. This is the version served by MeshCentral.com now and it does not have this issue. You can reinstall now if you like. Also, the 64bit version of the agent never had this problem. Hope it helps.

![a1](https://user-images.githubusercontent.com/1319013/59624975-08280480-90ed-11e9-8fc1-1eb104809a85.png)

**Comment by Ylianst** [comment]
Close this once as it's been fixed a while back and seems not to be a problem anymore.
