### ISSUE TITLE
The language of the Assistant menu on the Invite page is being displayed incorrectly.

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentral#2718]
Hi! Ylianst,
I am always thank you to Ylianst for this amazing software!
On the Invite page, only the language of the Assistant menu is in Japanese. And when you download and run Assistant, Korean and Japanese are mixed. I hope that all menus will be consistently available only in English or Korean.
By the way, I am Korean.

![assistant](https://user-images.githubusercontent.com/6889244/120472267-a4359e00-c3e0-11eb-84b2-bb56f84ccc7d.JPG)

**Comment by Ylianst** [comment]
Oh dear. I see a lot of Korean strings are in the Japanese translation. Thanks for pointing that out, working on it now.

**Comment by Ylianst** [comment]
Ok. I fixed the Korean in Japanese issue. That will be in next version of MeshCentral.

**Comment by Ylianst** [comment]
Hopefully this is better... Will be in the next version.

![image](https://user-images.githubusercontent.com/1319013/120542055-7ed47000-c39f-11eb-9849-b83da93d6886.png)

![image](https://user-images.githubusercontent.com/1319013/120542113-927fd680-c39f-11eb-996b-e204e35ae3b3.png)

**Comment by Ylianst** [comment]
This fix was published. Let me know if it's ok. If so, please close this issue. Thanks.

**Comment by kuksabong** [comment]
Hi! Ylianst,
I just upgraded meshcentral to the latest 0.8.55 version and checked and it still didn't solve the problem.

**Comment by kuksabong** [comment]
I am using both Korean and English in my browser.

![language](https://user-images.githubusercontent.com/6889244/120999783-77a8ca00-c7c4-11eb-84cc-dc5629870020.png)

**Comment by MailYouLater** [comment]
> And how can I set the language to English without being affected by the browser's language setting?

You can either add `&lang=en` <sub><sup>(or `?lang=en` if there's no other parameters there)</sup></sub> to the end of the URL, or you can go to your user settings, click the "Localization Settings" link and pick "en - English" from the Language options.

**Comment by kuksabong** [comment]
I already set the language to "en - English" in the Localization settings, but the invite page still outputs in Korean.

**Comment by Ylianst** [comment]
Korean/Japanese strings should be fixed now.
