### ISSUE TITLE
BUG new agents do not appear until the server is restarted

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [Ylianst/MeshCentral#3111]
Server 0.9.19.
When installing a new agent on a new computer, it does not appear in the web interface. At the same time, in the trace, we see the normal connection of the agent to the server. If you restart the Mesh Server service, the agent immediately connects and a device is created in the group.

**Comment by VINISHVV** [comment]
Can you try below trouble shooting method once?

Install new agent in a system
Stop the running meshagent service
Open command prompt.
Goto mesh agent folder
Type the commend "meshagent.exe run"

This will show the log, and also helps to fix the issues.

**Comment by Ylianst** [comment]
I have not seen this, but this problem has been reported before and was fixed by updating NodeJS. Before you update, please let us know:

- What operating system and OS version you are using on the server?
- What NodeJS version you are using?
- What database and database version you are using?

When, update NodeJS and let us know if it starts working.

**Comment by AntonAndreevichMoroz** [comment]
Debian 10 server OS
Meshcentral Server Version 0.9.20
Node.js version v14.17.4
Database in MongoDb config (db version v4.4.8)
The total number of active clients is slightly less than 300 pieces
NGINX is installed in front of Meshcentral as a reverse proxy

Here's an example of a computer that doesn't show up.
Computer OS in screenshots Wondows 8.1. But this problem also manifests itself on Windows 7 and Windows 10.
A manual launch of the agent looks normal.
![pc_mesh](https://user-images.githubusercontent.com/51225180/132827967-7ed8d6de-60b1-472b-baa4-3cfbafa508e2.jpg)

There is nothing critical in the agent's logs either.
[MeshAgent.log](https://github.com/Ylianst/MeshCentral/files/7142556/MeshAgent.log)

On the server side, in the trace, we see the connection from the agent side
![tracert_mesh](https://user-images.githubusercontent.com/51225180/132828080-b2b2af13-4b4c-43ac-a450-53c4a1309acb.JPG)

But it doesn't appear on the list.
![list_before_restart](https://user-images.githubusercontent.com/51225180/132828090-9ce7f8bb-56ef-4b77-a451-ae2f70b8987e.JPG)

If you restart the Meshcentral service on the server, but the connection immediately occurs automatically and the computer is registered.
![list_after_restart](https://user-images.githubusercontent.com/51225180/132828104-cf73b195-aada-43a8-84a0-eb7f807886ab.JPG)

**Comment by VINISHVV** [comment]
> Debian 10 server OS
> Meshcentral Server Version 0.9.20
> Node.js version v14.17.4
> Database in MongoDb config (db version v4.4.8)
> The total number of active clients is slightly less than 300 pieces
> NGINX is installed in front of Meshcentral as a reverse proxy
> 
> Here's an example of a computer that doesn't show up.
> Computer OS in screenshots Wondows 8.1. But this problem also manifests itself on Windows 7 and Windows 10.
> A manual launch of the agent looks normal.
> ![pc_mesh](https://user-images.githubusercontent.com/51225180/132827967-7ed8d6de-60b1-472b-baa4-3cfbafa508e2.jpg)
> 
> There is nothing critical in the agent's logs either.
> [MeshAgent.log](https://github.com/Ylianst/MeshCentral/files/7142556/MeshAgent.log)
> 
> On the server side, in the trace, we see the connection from the agent side
> ![tracert_mesh](https://user-images.githubusercontent.com/51225180/132828080-b2b2af13-4b4c-43ac-a450-53c4a1309acb.JPG)
> 
> But it doesn't appear on the list.
> ![list_before_restart](https://user-images.githubusercontent.com/51225180/132828090-9ce7f8bb-56ef-4b77-a451-ae2f70b8987e.JPG)
> 
> If you restart the Meshcentral service on the server, but the connection immediately occurs automatically and the computer is registered.
> ![list_after_restart](https://user-images.githubusercontent.com/51225180/132828104-cf73b195-aada-43a8-84a0-eb7f807886ab.JPG)

**Try to upgrade nodejs to 16.4.2**

**Comment by AntonAndreevichMoroz** [comment]
We've updated NodeJs to version 16. Unfortunately, the problem persists. What else can I check or what additional data can I provide for analysis?

**Comment by VINISHVV** [comment]
> We've updated NodeJs to version 16. Unfortunately, the problem persists. What else can I check or what additional data can I provide for analysis?

@AntonAndreevichMoroz 

I hope session recording is activated in your server. Can you try to disable the same for few hours and confirm the status.

**Comment by AntonAndreevichMoroz** [comment]
> > We've updated NodeJs to version 16. Unfortunately, the problem persists. What else can I check or what additional data can I provide for analysis?
> 
> @AntonAndreevichMoroz
> 
> I hope session recording is activated in your server. Can you try to disable the same for few hours and confirm the status.

Yes.  activated for 1 user.  and just recently it was turned on.  I'll try to turn it off.

**Comment by VINISHVV** [comment]
Please turn off the session recording and share your feedback.

**Comment by AntonAndreevichMoroz** [comment]
can't say 100%, but apparently disabling session recording helped to solve this.  Can session recording be used while maintaining the normal functionality of adding new agents?

**Comment by VINISHVV** [comment]
> can't say 100%, but apparently disabling session recording helped to solve this. Can session recording be used while maintaining the normal functionality of adding new agents?

I think session recording takes more bandwidth and server utalization of server resource. This affects agent connectivity..

@Ylianst - can you check this issue once?.

**Comment by Ylianst** [comment]
Oh. Just noticed this. Can someone go in "meshcentral-data" and see if there is anything in the "mesherrors.txt" file?

**Comment by Mfinadmin** [comment]
> Oh. Just noticed this. Can someone go in "meshcentral-data" and see if there is anything in the "mesherrors.txt" file?

@Ylianst
Meshcentral data not showing any error messages.

**Comment by VINISHVV** [comment]
@Ylianst
This is a natural issue i have noticed during session recording enabled.

I dont see any error logs in meshcentral-data folder till now.

**Comment by ONBET** [comment]
Same behavior on latest meshcentral

**Comment by VINISHVV** [comment]
@ONBET - Yes this issue still persists, If we disable session recording then all the New agents appear immedeatly.

**Comment by si458** [comment]
PLEASE FOLLOW #4449
