### ISSUE TITLE
Apache reverse proxy

### ISSUE THREAD

**Issue by amenolo** [Ylianst/MeshCentral#317]
AFAYK there's any chance to make MC (agents, web UI, console, file, and so on....) work through apache reverse proxy? Thanks!

**Comment by Ylianst** [comment]
Hi. The [MeshCentral Install Guide](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide-0.2.4.pdf) has instructions to install behind NGNIX and Traefik (sections 16 and 17). You should be able to use about the same instructions to install other reverse proxies like Apache and HAproxy.

Hope it helps,
Ylian

**Comment by amenolo** [comment]
Already tried that way, no luck :-(
Time to switch to Ngnix :-)

Thanks

**Comment by jsastriawan** [comment]
Probably this is related to Apache support websocket proxying. I haven't looked at using Apache to perform websocket reverse proxy.

**Comment by Ylianst** [comment]
I am a bit swamped with bugs & feature request, so I am not going to get to this in a while. If anyone successfully installed MeshCentral behind the Apache reverse proxy and can post the configuration file to do it, that would be greatly appreciated.

**Comment by b8two** [comment]
Hi All,

I was working on this today and I'd like to share what I found (using Various online help pages).

These modules will need to be loaded (Using apache for Windows as example)
"
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
"

The Virtual Host Configuration will need something along the lines of;

<VirtualHost *:443>  
  ServerName mesh.proxy.net 

RewriteEngine On
RewriteCond %{HTTP:UPGRADE} ^WebSocket$
RewriteCond %{HTTP:CONNECTION} Upgrade$
RewriteRule /(.*) ws://127.0.0.1:4430/ [P]

ProxyPass / http://127.0.0.1:4430/ 

ProxyRequests Off
</VirtualHost>

I hope this helps anyone with this problem in the future.

**Comment by b8two** [comment]
Not a Complete Solution.

If I'm already authenticated in the browser, I can use everything as normal with TlsOffload configured. (Should this be a WAN or LAN address?)
If I need to authenticate, then I can't log in but if I change to NoTls, then everything works again except adding clients have connections with ws:\\ when they should have wss:\\

Perhaps there is another rewrite rule needed?

**Comment by GRIFFCOMMca** [comment]
I can confirm this is a bug, after the research i have done it appears to be an Apache "issue" with how it handles both http and WS protocols down the same proxy pipe.  Assuming you know how to configure a basic proxypass, the below works.

LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
<VirtualHost 0.0.0.0:443>
  ServerName server.com
  SSLCertificateFile "C:/Program Files/INTERNET/Apache24/SSL/cert.crt"
  SSLCertificateKeyFile "C:/Program Files/INTERNET/Apache24/SSL/key.key"
  SSLEngine on
  SSLProxyEngine on
  <Location />
    ProxyPass http://127.0.0.1:4430/
  </Location>
</VirtualHost>

However this will result in the login page but UNABLE to login

Using both
ProxyPass ws://127.0.0.1:4430/
ProxyPass wss://127.0.0.1:4430/

Results in an entry in the error log of
No protocol handler was valid for the URL / (scheme 'wss'). If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule.

Clearly i have the module loaded, however research says with Apache its likely the web application error trying to move socket data over the same URL as http data, so Apache has no idea how to move the data, thus results in the error in the log file

The main issue i see with this would be only able to ProxyPass one protocol over each URL, so https://127.0.0.1:4330 can only move HTTP data and not Socket data (with regards Apache HTTP server).  To move socket data it appears a URL would need to be added.  This seems to agree with Apache help file on the subject.

https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html

Which uses ProxyPass "/wss2/" "wss://echo.websocket.org/", you can see its has /wss2/ in the URL for this to work, this seperating that URL from HTTP only data.

Faily sizable bug really, as i would of expected MeshCentral to work no issues with Apache server.

**### This is now holding up deployment.**

**Comment by GRIFFCOMMca** [comment]
UPDATE
The AGENT works, however all connections are from the local machine (127.0.0.1), this doesnt surprise me, its something i will look in to as its clearly Apache not sending the correct headers over.  Might also be connected to not telling MESH that the TLS is off loaded.

Need input from the developer here...

**Comment by Ylianst** [comment]
I will need to install Apache, configure it and give this a run. I fully expect MeshCentral to work with "tlsoffload" enabled. A quick look at the mod_proxy documentation shows that the right headers are being added (X-Forwarded-Host...) so, I fully expect this to work. This said, I will try to put some time on this to see if I can make it work.

**Comment by GRIFFCOMMca** [comment]
> I will need to install Apache, configure it and give this a run. I fully expect MeshCentral to work with "tlsoffload" enabled. A quick look at the mod_proxy documentation shows that the right headers are being added (X-Forwarded-Host...) so, I fully expect this to work. This said, I will try to put some time on this to see if I can make it work.

Thanks, i also expected it to work, however it took me a few days to get the above working, its not however all IP addresses are showing as 127.0.0.1 in MeshCentral, so either Apache isnt doing it or MeshCentral isnt picking them up.

I have another server (email server) thats https doing a reverse proxy, they also sees everything as 127.0.0.1 so it appears its an Apache http issue (from what i can see).

When you are testing, please make sure to use full domain names as most who will want to offload will be as they only have 1 external IP address with other websites sitting on the Apache server in use, so any cert checking will need to be via the DNS name not just the IP address to the Apache server.

**Comment by Ylianst** [comment]
I made progress on using Apache as a reverse proxy. I encountered #439, once I get that fixed, I should be able to document the results. I got it to work with TLSOffload enabled.

**Comment by GRIFFCOMMca** [comment]
Hi


I found the reason i was unable to login had something to do with the SSL 
offload and the TCP transport... not sure which.  I bet if you turn the SSL 
Offload off AND use https://127.0.0.1:port to MeshCentral using Apache to 
SSL Proxy your likely be able to login, if so then its something to do with 
with Apache / Mesh SSL system.


Someone else had this issue, when he turned off the SSL altogether in Mesh 
Central the Apache reverse Proxy worked.


   Many Thanks
   Ashley
   Network Specialist : Manager
   © Copyright 2018 ~ GRIFFCOMM inc

   1 226 485 1002 x111
   ashley.griffin@griffcomm.ca
   	
Service	
Phones	
Backup	
Video Surveillance	
Managed Service

**Comment by b8two** [comment]
Hi Ylianst, 

To handle all websocket connections, these rules work. 

RewriteEngine On
RewriteCond %{HTTP:UPGRADE} ^WebSocket$
RewriteCond %{HTTP:CONNECTION} Upgrade$
RewriteRule /(.*) ws://127.0.0.1:4430/ [P]

**Comment by b8two** [comment]
Hi Ylianst,

Using Apache for a reverse proxy, I came in to an issue using the Windows Version and I have now discovered this is due to the default ThreadsPerChild limit set to 64. This is important as each Websocket consumes a thread, hence I reached the limit quickly with all the clients connecting in.
Hence you may want to mention this in the documentation.

I came across this page today which may help with your Apache reverse proxy documentation;
https://www.happyassassin.net/2018/11/23/reverse-proxying-websockets-with-apache-a-generic-approach-that-works-even-with-firefox/

Also another way to do this without "tlsoffload" function and associated performance benefits is to use the self signed certificates and configure Apache to ingore what is wrong with the certificates using these parameters;

  SSLProxyEngine on
  SSLProxyVerify none
  SSLProxyCheckPeerCN off
  SSLProxyCheckPeerName off
  SSLProxyCheckPeerExpire off

I'm having a similar issue to GRIFFCOMMca regarding logging of IP addresses in MeshCentral. They all are shown as the Apache reverse proxy machine IP address. In my case, the reverse proxy is on another machine in a DMZ environment. It is also the case on the "My Devices" Tab where all devices addresses are the reverse proxy IP address. I'm not too concerned but I don't think this is how you want it to behave.

**Comment by GRIFFCOMMca** [comment]
The clarify, the IP addresses shown on the My Devices page are the CORRECT WAN IP addresses, its only in the LOG file that i seem to see 127.0.0.1 alot.

When i first set up the reverse proxy before Ylain fixed it all the devices IP addresses were the Apache Web server, this was fixed after Ylain "fixed" the code somehow.

Does this socket limit have anything to do with the ticket i opened here https://github.com/Ylianst/MeshCentral/issues/460

**Comment by Sleepw4lker** [comment]
I can confirm the solution provided by [Yilanst](https://github.com/Ylianst/MeshCentral/issues/317#issuecomment-525048548) as well as the one suggested by [GRIFFCOMca](https://github.com/Ylianst/MeshCentral/issues/317#issuecomment-525118355) are working. I also observe that Client Connections are logged as 127.0.0.1 as 
[GRIFFCOMca](https://github.com/Ylianst/MeshCentral/issues/317#issuecomment-525139090) already mentioned.

**Comment by Ylianst** [comment]
FYI. I published MeshCentral 0.4.0-o yesterday that fixed the IP address in the logs. So, it should show the correct IP address now.

**Comment by GRIFFCOMMca** [comment]
I can confirm this is now working through the Apache reverse proxy

**Comment by Sleepw4lker** [comment]
Confirmed as well

**Comment by b8two** [comment]
Hi,  I still don't have the correct IP addresses in MC.

My configuration is using Two Machines (Apache Reverse Proxy in a DMZ) via a router with Mesh Central Server on another. Both have different subnet mask IP range and prior to the v0.4.0-i update I could add extra clients no problem (~90). Even with the latest update 0.4.0-y all agents are seen connecting from the DMZ, as are the users

**Comment by b8two** [comment]
I changed the TlsOffload from the Public IP to the Private LAN IP and now the agent IP are indcatative of the origin.

**Comment by desarrollocdb** [comment]
Did anyone get an apache2 functional configuration?

**Comment by Sleepw4lker** [comment]
My fully working config files for Apache and MC.

```
<VirtualHost *:443>

        ServerName mesh.mydomain.tld
        ServerAdmin postmaster@mydomain.tld

	Alias /robots.txt /var/www/html/robots.txt

        RewriteEngine on
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteCond %{HTTP:Connection} upgrade [NC]
        RewriteRule . "ws://127.0.0.1:8081%{REQUEST_URI}" [P]

        ProxyPassMatch ^/robots.txt !
        ProxyPass / http://127.0.0.1:8081/ connectiontimeout=86400 timeout=30
        ProxyPassReverse / http://127.0.0.1:8081/
        ProxyPreserveHost On

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        SSLEngine on

        SSLCertificateFile /etc/letsencrypt/live/mesh.mydomain.tld/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/mesh.mydomain.tld/privkey.pem
        SSLCACertificateFile /etc/letsencrypt/live/mesh.mydomain.tld/chain.pem
        SSLUseStapling on

 </VirtualHost>
```

```
{
  "settings": {
    "cert": "mesh.mydomain.tld",
    "Port": 8081,
    "RedirPort": 8082,
    "AliasPort": 443,
    "AgentPong": 300,
    "TLSOffload": "127.0.0.1",
    "Minify": 1,
    "Wanonly": true
  },
  "domains": {
    "": {
        "newAccounts" : 0,
        "certUrl": "https://mesh.mydomain.tld"
    }
  }
}
```

**Comment by desarrollocdb** [comment]
> My fully working config files for Apache and MC.
> 
> ```
> <VirtualHost *:443>
> 
>         ServerName mesh.mydomain.tld
>         ServerAdmin postmaster@mydomain.tld
> 
> 	Alias /robots.txt /var/www/html/robots.txt
> 
>         RewriteEngine on
>         RewriteCond %{HTTP:Upgrade} websocket [NC]
>         RewriteCond %{HTTP:Connection} upgrade [NC]
>         RewriteRule . "ws://127.0.0.1:8081%{REQUEST_URI}" [P]
> 
>         ProxyPassMatch ^/robots.txt !
>         ProxyPass / http://127.0.0.1:8081/ connectiontimeout=86400 timeout=30
>         ProxyPassReverse / http://127.0.0.1:8081/
>         ProxyPreserveHost On
> 
>         ErrorLog ${APACHE_LOG_DIR}/error.log
>         CustomLog ${APACHE_LOG_DIR}/access.log combined
> 
>         SSLEngine on
> 
>         SSLCertificateFile /etc/letsencrypt/live/mesh.mydomain.tld/fullchain.pem
>         SSLCertificateKeyFile /etc/letsencrypt/live/mesh.mydomain.tld/privkey.pem
>         SSLCACertificateFile /etc/letsencrypt/live/mesh.mydomain.tld/chain.pem
>         SSLUseStapling on
> 
>  </VirtualHost>
> ```
> 
> ```
> {
>   "settings": {
>     "cert": "mesh.mydomain.tld",
>     "Port": 8081,
>     "RedirPort": 8082,
>     "AliasPort": 443,
>     "AgentPong": 300,
>     "TLSOffload": "127.0.0.1",
>     "Minify": 1,
>     "Wanonly": true
>   },
>   "domains": {
>     "": {
>         "newAccounts" : 0,
>         "certUrl": "https://mesh.mydomain.tld"
>     }
>   }
> }
> ```

Thanks, this has helped me

**Comment by OutbackMatt** [comment]
On this issue...

I run Apache web servers
I have a meshcentral server on same machine
I have reversed proxied from port 443 (Apache) to port 444 (MeshCentral Server) and it works fine (thanks to the above posts)

What I'd like to do is create Mesh Client downloads that use port 443 rather than port 444.
How can I do this?
Currently I install then modify the MeshAgent.msh file

**Comment by MailYouLater** [comment]
@OutbackMatt: Did you set the `AliasPort` to `443`?

**Comment by OutbackMatt** [comment]
Ah, no I didn't

Have done now thanks

**Comment by Ylianst** [comment]
Nice! Thanks @MailYouLater. Yes, that is exactly what "AliasPort" is for.

**Comment by OutbackMatt** [comment]
This is actually giving me some grief...

If I set a aliasPort any new 'add agent' doesn't want to connect
I don't have TLS offload set, as If I turn that off the main web page stops being HTTPS, and won't load due to my HSTS

I'd like to use the Lets Encrypt certificates for my subdomian that I already have in (ubuntu) /etc/letsencrypt/live/sub.fqdn/ but I can't seem to work that out. (I can set a symbolic link, but I can't seem to have different permissions for the link)

I want to pass WSS not WS (which I'm currently doing) between the apache2 Reverse Proxy and tmy mesh

**Comment by MordyT** [comment]
While this thread has a bunch of example, most of them are focused on edge security (security at the proxy, ignoring everything inside).

Here is a more standard, fully secure, config.

1. Apache reverse proxy with these mods loaded:
 proxy_module (shared)
 proxy_http_module (shared)
 proxy_wstunnel_module (shared)

2. Working Mesh install. With a direct connection (inside the network) you should have working SSL -copy the cert files into the correct directories in MC, restart services. https://mesh.domain.tld (and http) should work and load correctly from another PC on lan.

3) A config looking like this:
`{
   "settings": {
      "AllowHighQualityDesktop": true,
	  "cert": "mesh.domain.tld", 
	  "_SelfUpdate": true,
          "minify": true,
	  "Port": 443,
	  "RedirPort": 80,
	  "SessionKey": "<randomstrongstring>",
	  "ExactPorts": "true"
   }, 
   "domains": {
      "": {
         "title": "Mesh", 
         "newaccounts": false,
		 "certUrl": "https://mesh.domain.tld/"
      }
   }
}`

4) Virtual host file that looks like this
`<IfModule mod_ssl.c>
        <VirtualHost *:443>
                ServerAdmin webmaster@localhost
                ServerName mesh.domain.tld
                
				ProxyPreserveHost On
                ProxyPass "/" "https://mesh.domain.tld/"
                ProxyPassReverse "/" "https://mesh.domain.tld/"
                
				RewriteEngine on
                RewriteCond %{HTTP:Upgrade} websocket [NC]
                RewriteCond %{HTTP:Connection} upgrade [NC]
                RewriteRule . "wss://mesh.domain.tld%{REQUEST_URI}" [P]
                
				ErrorLog ${APACHE_LOG_DIR}/error.log
                CustomLog ${APACHE_LOG_DIR}/access.log combined
                
				SSLEngine on
                SSLProxyEngine On
                SSLCertificateFile      /etc/ssl/certs/cert.pem
                SSLCertificateKeyFile /etc/ssl/private/key.key
                SSLProtocol TLSv1.2
                SSLCipherSuite EECDH+AESGCM:EDH+AESGCM
                SSLHonorCipherOrder on
				
                <FilesMatch "\.(cgi|shtml|phtml|php)$">
                                SSLOptions +StdEnvVars
                </FilesMatch>
                
				<Directory /usr/lib/cgi-bin>
                                SSLOptions +StdEnvVars
                Options FollowSymLinks
                AllowOverride All
                </Directory>
				
        </VirtualHost>
</IfModule>
`

Either redirect 80 at the proxy or pass through

I use the same wildcard SSL cert for both apache and the mesh server

**Comment by nroach44** [comment]
Per the setup guide, as MPS/CIRA is a binary protocol, will Apache even be able to reverse proxy that? I know it doesn't seem to have the same capability as nginx/haproxy.

Would we be able to port forward it, for the situation of "public facing proxy" and "internal only app server"?

**Comment by Ylianst** [comment]
For CIRA, you will need to just TCP forward the connection. Intel AMT does not support TLS-SNI (Server Name Indication) so there is no way to perform a reverse proxy on the CIRA connection and route the connection correctly. The best you can do is terminate the TLS in the reverse proxy if you like and forward the connection to MeshCentral.

If you do terminate the TLS on the reverse proxy, you need to use the long-standing self-signed certificate that MeshCentral uses on the MPS/CIRA port. Hope that makes sense.

**Comment by Ylianst** [comment]
FYI. I am going to close this issue. However, please feel free to open new issues on AMT/CIRA, etc.
