### ISSUE TITLE
Impossible to get a Let's Encrypt certificate

### ISSUE THREAD

**Issue by HerveSC** [Ylianst/MeshCentral#3245]
Hi!

First, thanks a lot for your great work, we are currently adopting MeshCentral in place of AnyDesk to be fully in control and autonomous.
There are few things that would be great if they are added to use it fully for remote work also, but I will open later a feature request issue.

Back to the issue: on our newly deployed VM dedicated to MeshCentral, I'm not able to get a Let's Encrypt certificate, even though Let's Debug status is Ok and I am able to get a certificate for my domain on this VM through certbot without any issue.
The VM is behind a reverse proxy with ports 80 and 443 exposed.

The traces I get from the debug mode:
```
MeshCentral HTTP redirection server running on port 80.
CERT: LE: Getting certs from local store (Staging)
CERT: LE: No certificate files found
MeshCentral v0.9.41, WAN mode.
MeshCentral Intel(R) AMT server running on my.company.ovh:4433.
MeshCentral HTTPS server running on my.company.ovh:443.
CERT: LE: Got no certificates, asking for one now.
CERT: LE: Generating private key...
CERT: LE: Setting up ACME client...
CERT: LE: Creating certificate request...
CERT: LE: Requesting certificate from Let's Encrypt...
CERT: LE: Failed to obtain certificate: connect ETIMEDOUT xxx.xxx.xxx.xxx:80
```
I've also tried to switch to production mode, but same issue. The letsencrypt-cert folder stays of course empty.

My (not clean) config file:
```
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "Cert": "my.company.ovh",
    "MongoDb": "mongodb://127.0.0.1:27017/meshcentral",
    "WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "newAccounts": false,
      "_userNameIsEmail": true,
      "loginkey": ["secret_key"],
      "passwordRequirements": {
          "min": 8,
          "max": 128,
          "upper": 1,
          "lower": 1,
          "numeric": 1,
          "nonalpha": 1,
          "force2factor": true
      }
    }
  },
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "me@mycompany.fr",
    "names": "my.company.ovh",
    "production": false
  }
}
```

Additionnal information:
Ubuntu 20.04 LTS
Node v14.18.1

For now, I did get around the issue by manually placing the certificate I got from certbot in meshcentral-data (as a common certificate) and I could to some automation for this, but the Let's Encrypt built-in automation would be way better.

Best regards,

Hervé

**Comment by Ylianst** [comment]
By the way, I am coming out with a [YouTube video on this exact topic next week](https://www.youtube.com/watch?v=a4F1ayu7XWo).

Your MeshCentral configuration looks correct, but is seems like Let's Encrypt can't connect to port 80 of your server. First, try [https://letsdebug.net/](https://letsdebug.net/), enter your domain name and select "HTTP-01" as the testing method, this is the method MeshCentral will use to get your certificate.

- Is it possible that your using a AWS Security Group (or other such policy) that blocks most IP addresses from connecting to port 80 on your server?
- Does you NGINX port 80 policy redirect users to port 443, or does it forward traffic to port 80 of MeshCentral?

In order for this to work, MeshCentral needs to receive the HTTP/80 request from Let's Encrypt so that it can answer the challenge. From the error given by Let's Encrypt, it can't even connect to port 80.

Also, don't do `"production": true` until you get a staging certificate, otherwise you will likely get blocked from the service for a while.

**Comment by HerveSC** [comment]
- As said, Let's Debug with HTTP01 is OK and I'm able to get a Let's Encrypt certificate with certbot using HTTP-01.
- There is no specific IP filtering policy.
- Port 80 is redirected to port 80 of MeshCentral.

So, for me, my server is perfectly accessible by Let's Encrypt. This is why I dared to open this issue since I really think that something in not working properly with MeshCentral Let's Encrypt implementation.

**Comment by HerveSC** [comment]
And to prove my point, here is the trace of certbot I obtained when getting my Let's Encrypt certificate manually:

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Enter email address (used for urgent renewal and security notices)
 (Enter 'c' to cancel): me@mycompany.fr

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Please read the Terms of Service at
https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf. You must
agree in order to register with the ACME server. Do you agree?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(Y)es/(N)o: Y

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Would you be willing, once your first certificate is successfully issued, to
share your email address with the Electronic Frontier Foundation, a founding
partner of the Let's Encrypt project and the non-profit organization that
develops Certbot? We'd like to send you email about our work encrypting the web,
EFF news, campaigns, and ways to support digital freedom.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(Y)es/(N)o: No
Account registered.
Please enter the domain name(s) you would like on your certificate (comma and/or
space separated) (Enter 'c' to cancel): my.company.ovh
Requesting a certificate for my.company.ovh

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/my.company.ovh/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/my.company.ovh/privkey.pem
This certificate expires on 2022-02-01.
These files will be updated when the certificate renews.
Certbot has set up a scheduled task to automatically renew this certificate in the background.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

**Comment by Ylianst** [comment]
Oh wow... you have me stumped. I have no idea.

An alternative is that since you are running a reverse proxy in front of MeshCentral, you could have the reverse proxy get the Let's Encrypt cert and you would use in the "settings" section:

```
"tlsoffload": "x.x.x.x"
```

Where x.x.x.x is the internal IP address of the reverse proxy. And then this line in the domain section:

```
"certurl": "https://myserver.example.com"
```

This specifies where MeshCentral can fetch the TLS certificate the agents will see when connecting.

That way, you don't have MeshCentral managing your TLS certificate at all.

**Comment by HerveSC** [comment]
When I enabled the debug traces, I also enabled the web server requests traces with the webrequest argument, but there wasn't anything interesting (only the traffic from my computer) so I filtered them when posting my traces.

And yes, I've seen that MeshCentral was supporting TLS offloading, but I prefer to keep an end to end certificate since I also have internal traffic which does not go through our reverse proxy.
But thanks for the suggestion!

I'm sorry that I don't know what I can do more to help you find where this issue comes from :(

**Comment by Ylianst** [comment]
The best I can offer is that if you send me access to a test server, I can login it and debug it. If you opt to do that, please use [my contact info and PGP key to send me encrypted data](https://www.meshcommander.com/contact-information). Hopefully I can find a problem in MeshCentral.

**Comment by nzalev** [comment]
@HerveSC I have multiple instances of LE working without issue, but I have only tested with Nginx as a reverse proxy. Typically `CERT: LE: Failed to obtain certificate: connect ETIMEDOUT xxx.xxx.xxx.xxx:80` indicates that LE was not able to connect back to Meshcentral.

What reverse proxy are you using? Can you post the config? I will try to reproduce the issue.

**Comment by nzalev** [comment]
Further to the above, 
Without a reverse proxy:
<pre>noah@tts01:~/meshcentral$ node node_modules/meshcentral/ --debug cert
MeshCentral HTTP redirection server running on port 80.
CERT: LE: Getting certs from local store (Staging)
CERT: LE: No certificate files found
MeshCentral v0.9.45, WAN mode.
MeshCentral Intel(R) AMT server running on tts.zalev.ca:4433.
MeshCentral HTTPS server running on tts.zalev.ca:443.
CERT: LE: Got no certificates, asking for one now.
CERT: LE: Generating private key...
CERT: LE: Setting up ACME client...
CERT: LE: Creating certificate request...
CERT: LE: Requesting certificate from Let&apos;s Encrypt...
CERT: LE: Succesful response to challenge.
CERT: LE: Succesful response to challenge.
CERT: LE: Succesful response to challenge.
CERT: LE: Succesful response to challenge.
CERT: LE: Got certificate.
CERT: LE: Performing server restart...
Updating server certificates...
MeshCentral HTTP redirection server running on port 80.
CERT: LE: Getting certs from local store (Staging)
CERT: LE: Reading certificate files
CERT: LE: Setting LE cert for default domain.
MeshCentral v0.9.45, WAN mode.
MeshCentral Intel(R) AMT server running on tts.zalev.ca:4433.
MeshCentral HTTPS server running on tts.zalev.ca:443.
CERT: LE: Certificate has 89 day(s) left.
CERT: LE: Certificate is ok.
</pre>


With a properly configured reverse proxy (Nginx)

<pre>noah@tts01:~/meshcentral$ node node_modules/meshcentral/ --debug cert
MeshCentral HTTP redirection server running on port 1080.
CERT: LE: Getting certs from local store (Staging)
CERT: LE: No certificate files found
MeshCentral v0.9.45, WAN mode.
MeshCentral Intel(R) AMT server running on tts.zalev.ca:4433.
MeshCentral HTTPS server running on tts.zalev.ca:1443, alias port 443.
CERT: LE: Got no certificates, asking for one now.
CERT: LE: Generating private key...
CERT: LE: Setting up ACME client...
CERT: LE: Creating certificate request...
CERT: LE: Requesting certificate from Let&apos;s Encrypt...
CERT: LE: Succesful response to challenge.
CERT: LE: Succesful response to challenge.
CERT: LE: Succesful response to challenge.
CERT: LE: Succesful response to challenge.
CERT: LE: Got certificate.
CERT: LE: Performing server restart...
Updating server certificates...
MeshCentral HTTP redirection server running on port 1080.
CERT: LE: Getting certs from local store (Staging)
CERT: LE: Reading certificate files
CERT: LE: Setting LE cert for default domain.
MeshCentral v0.9.45, WAN mode.
MeshCentral Intel(R) AMT server running on tts.zalev.ca:4433.
MeshCentral HTTPS server running on tts.zalev.ca:1443, alias port 443.
CERT: LE: Certificate has 89 day(s) left.
CERT: LE: Certificate is ok.
</pre>


The following config is from Nginx:
<pre>server <span style="background-color:#1A92AA">{</span>
        listen 80;
        server_name tts.zalev.ca;
        location / {
                proxy_pass http://127.0.0.1:1080;
                proxy_http_version 1.1;
                proxy_set_header X-Forwarded-Host $host:$server_port;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
<span style="background-color:#1A92AA">}</span>
</pre>

Since Nginx is on the same host as meshcentral and listening on port 80, meshcentral must have its ports changed:
<pre>  &quot;settings&quot;: {
    &quot;cert&quot;: &quot;tts.zalev.ca&quot;,
    &quot;WANonly&quot;: true,
    <b>&quot;port&quot;: 1443,
    &quot;aliasPort&quot;: 443,
    &quot;redirPort&quot;: 1080,
    &quot;redirAliasPort&quot;: 80,</b>
    &quot;mariadb&quot;: {

    }
</pre>

I noticed that you are using port 80 in your config with the reverse proxy. If the reverse proxy and meshcentral are on the same host, this config is not usable and you must set up port aliasing in meshcentral.

Additionally, you must make sure that the `name` from the le-config matches your vhost block in your reverse proxy, or the request will not make it to meshcentral.

**Comment by alesribic73** [comment]
Hi

I have the same problem. MeashCentral is accessible from outside tested with letsdebug. Error is the same: 
Failed to obtain certificate: connect ETIMEDOUT 195.78.xxx.xxx:80

I can give you remote access if you have time to look at

**Comment by Ylianst** [comment]
This problem has been fixed in #3296. Update to MeshCentral v0.9.54 or better and add the following line in the config.json:

```
  "letsencrypt": {
    "email": "myemail@myserver.com",
    "names": "myserver.com,customer1.myserver.com",
    "skipChallengeVerification": false,                                          <-------------
    "production": false
  }
```

This should fix it. It's because the Let's Encrypt library I use does a self-check to make sure everything is ok before contacting Let's Encrypt. This line will disable the self-check.

Let me know if that solves it.

**Comment by HerveSC** [comment]
Oh god I completely forgot to answer you back, I'm so sorry...
I will try the fix today if possible and tell you if it's better with this configuration. Thanks a lot!

**Comment by alesribic73** [comment]
I have disabled loopback and add a line "skipChallengeVerification": true,
i will see after a month if cert will be renewed.

**Comment by HerveSC** [comment]
Hello Ylian,

I've updated to v0.9.55 this morning and it still doesn't work when adding the line "skipChallengeVerification": false
'''
  "letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "me@mycompany.fr",
    "names": "my.company.ovh",
    "skipChallengeVerification": false,
    "production": false
  }
'''

The result with cert debug:
'''
MeshCentral HTTP redirection server running on port 80.
CERT: LE: Getting certs from local store (Staging)
CERT: LE: No certificate files found
MeshCentral v0.9.55, WAN mode.
MeshCentral Intel(R) AMT server running on my.company.ovh:4433.
MeshCentral HTTPS server running on my.company.ovh:443.
CERT: LE: Got no certificates, asking for one now.
CERT: LE: Generating private key...
CERT: LE: Setting up ACME client...
CERT: LE: Creating certificate request...
CERT: LE: Requesting certificate from Let's Encrypt...
CERT: LE: Failed to obtain certificate: connect ETIMEDOUT xxx.xxx.xxx.xxx:80
'''

**Comment by alesribic73** [comment]
It is working for me. Try with TRUE argument. Here is my line: "skipChallengeVerification": true,

**Comment by HerveSC** [comment]
Good news! It works to here with this parameter at true. I was dumb enough to simply copy/paste the configuration of Ylian without thinking about what I was adding.
So in the end, this is the self check that was blocking everything. I'm now on production with a Let's Encrypt certificate obtained through MeshCentral.

Thanks @Ylianst and @alesribic73 

I can close the issue :)
