### ISSUE TITLE
Bug: Blinking Cursor during remote access on Windows PCs

### ISSUE THREAD

**Issue by johnnyq** [Ylianst/MeshCentral#3663]
When we remote in to a Windows computer the user states that their cursor is blinking non stop. This doesn't appear to be an issue for our MacOS or Linux clients.

**Comment by Ylianst** [comment]
When you say "blinking cursor", I presume you are talking about the mouse cursor. This happens on some Windows computers and Bryan is working right now on a solution for this. It blinks each time the agent captures the display and Bryan is going to be using a better capture system that should solve this.

**Comment by johnnyq** [comment]
Fantastic! Thanks @krayon007 and @Ylianst

**Comment by dooley74** [comment]
Is this bug the same as this one?
https://github.com/Ylianst/MeshCentral/issues/357

**Comment by krayon007** [comment]
Yes, it is the same.

**Comment by dooley74** [comment]
How is the fix for this progressing?

**Comment by krayon007** [comment]
Still going on. I have a bunch of things going at the same time, but I hope to have the first rev of it working in the coming weeks.

**Comment by dooley74** [comment]
Any progress on resolving this?

**Comment by krayon007** [comment]
Not yet, I got sidetracked with some higher priority bug fixes. I plan on trying to complete the KVM overhaul this quarter tho.

**Comment by dooley74** [comment]
How goes the KVM overhaul?

**Comment by openncomp** [comment]
I thought this was in the order of things and did not expect that this feature could be solved.

**Comment by DevOps-88** [comment]
Hello

Has this bug been fixed in a new version?

**Comment by si458** [comment]
@DevOps-88 development is on hold https://github.com/Ylianst/MeshCentral/discussions/4795
if you can patch it yourself,we are happy to accept pull requests! 👍

**Comment by wizarddev038** [comment]
Hello, everyone. Thank you very much for creating such an amazing remote control system. I've been using it for about 2 months now and I'm really thrilled about the project.

Recently I discovered mouse cursor blinking error in the project. I studied the project and found out that agent was using CAPTUREBLT option when capturing the desktop. This was the cause of the mouse blink and I solved the problem by deleting this option.

I hope my solution would be helpful to all our users. Regards

**Comment by johnnyq** [comment]
@wizarddev038 Please submit a pull request we could all benefit off this Thanks

**Comment by wizarddev038** [comment]
Would you invite me as a collaborator in MeshAgent? I'd like to commit myself for the success of MeshAgent.

**Comment by si458** [comment]
@wizarddev038 sadly that's down to @Ylianst , but if u submit a PR in the MeshAgent repo I'm sure he will accept it!

**Comment by wizarddev038** [comment]
I submitted a pull request to Ylian's repository

**Comment by johnnyq** [comment]
is this now merged I cant tell, I do know im still getting the blinking cursor

**Comment by wizarddev038** [comment]
It's not merged. You can obviously see that it's still on request.

**Comment by johnnyq** [comment]
Thanks @wizarddev038 
Is there anything blocking this merge, or maybe just forgot about?

**Comment by si458** [comment]
Is been merged just need to build new agents which is in the works

**Comment by johnnyq** [comment]
Excellent news! Thanks for clarifying @si458 and thank you for your continued support towards meshcentral

**Comment by wizarddev038** [comment]
> Excellent news! Thanks for clarifying @si458 and thank you for your continued support towards meshcentral

If you have any questions, contact me. My email address is wizard38.software@gmail.com

**Comment by rossmarkflo** [comment]
Was this ever released? Is there a minimum agent version?

**Comment by si458** [comment]
@rossmarkflo the fix has been merged in the meshagent repo and u can built it yaself! But no releases sorry
However I'm hoping next week to do a few builds of the meshagent for people to try before I upload them to the repo! So stay posted!

**Comment by rossmarkflo** [comment]
sounds great -I can wait - was just curious..

**Comment by dhcpy** [comment]
Hello,  sorry for this question, I'm super new with MC, just installed last week. Blinking cursors on all indows 10/11 machines.
Can you help me on how do I build the build the agents?

**Comment by devwizard038** [comment]
Hi. How are you? The agent is built with Visual Studio. You can build this
with Visual Studio 2022. The cursor is blinking because there was a problem
with bitblt, if my memory serves me. Please check the updates. If you have
any question, please contact me via email or other chatting apps. I'm
always open.

**Comment by efschu** [comment]
I have recently installed 1.1.30, and I still see this bug. Thought the cursor blink patch was merged? I'm wrong?

**Comment by si458** [comment]
It's been merged but no new agents have been released so you will still see this until we release new agents

**Comment by Catbirby** [comment]
Hi All,

I'm running into this issue on a fair amount of PCs. The main issue is that it sometimes sticks and continues to happen long after we're finished with our remote session. 

I'm more than willing to compile the newer MeshAgent and have everything setup to do so (I think). But beyond hitting the build option in VS2022 (which compiles and gives an .exe that runs) I'm at a loss on how to actually use the finished product and/or what I need to configure.

Am I missing some documentation or a guide on how to correctly build and deploy the MeshService/MeshCmd files? 

Also should I be compiling based off of the Master branch to get this patch?

P.S. Thanks for the awesome product!

**Comment by chiucq** [comment]
Anyone can share the compiled patch to update the agent file. The blinking casued managed PC's user complaint about hurting their eye-sight.  Thanks!

**Comment by si458** [comment]
@chiucq the new agents are already included in the latest meshcentral releases, u just have to move files around and test, then report back if all is good!
https://github.com/Ylianst/MeshCentral/issues/6162#issuecomment-2620057495

**Comment by dhcpy** [comment]
> [@chiucq](https://github.com/chiucq) the new agents are already included in the latest meshcentral releases, u just have to move files around and test, then report back if all is good! [#6162 (comment)](https://github.com/Ylianst/MeshCentral/issues/6162#issuecomment-2620057495)

Could you please give some directions on where to find and how to upgrade the agents? I have upgraded the central to version 1.1.38, according to the version check, as of today is the latest. Then I reinstall the agent, from the link generated from the server. But it does not seem to update the version. The agent version on the clients, its stuck at "2022-Dec-2 1142:16-0800"

**Comment by si458** [comment]
@dhcpy follow the link in that above post and follow the steps on how to use the new test agents https://github.com/Ylianst/MeshCentral/issues/3663#issuecomment-2661340675

**Comment by si458** [comment]
finally fixed with 1.1.41 and 1.1.42

**Comment by dooley74** [comment]
What's the recommended process for updating the agents?

**Comment by si458** [comment]
If you don't have `noAgentUpdate: 1` set in your config.json, then the agents will auto update themselves
