### ISSUE TITLE
0.3.9-c failed on all Windows Servers 2008R2-2019

### ISSUE THREAD

**Issue by TitovLab** [Ylianst/MeshCentral#401]
Hello!
Apparently, version 0.3.9-c does not work on Windows Server 2008R2/2012/2012R2/2016/2019.
After upgrading from version 0.3.6-n to version 0.3.9-c, after a few seconds, all servers running Windows Server became inactive and after two hours did not work.
There are several dozens of servers, different configurations, from different countries, there is nothing in common between them.
Powered virtual machine with Windows 2012R2, install the latest version of MeshAgent on it, it is active in MeshCentral, but it is impossible to connect to it, after clicking Connect, the status becomes "Setup..." and that’s it.
It is impossible to stop the MeshAgent service - it hangs, only through the killing of the process.

There are no errors in the logs on the client side, on the server there is only one error, but most likely it is not connected with this:
```
-------- 8/3/2019, 9:28:09 PM ---- 0.3.9-c --------

the options [useNewUrlParser] is not supported
```

Quickly install a clean CentOS6 machine and MeshCentral 0.3.9-c without support for MongoDB and Windows Server 2019 - same error: the agent is active, it is impossible to connect, the MeshAgent service freezes.

Perhaps the matter is in the new functionality for checking the installed antivirus and the status of its updates?
If you need any additional information, please let me know.

**Comment by TitovLab** [comment]
Windows Servers fails only in 0.3.9-c.
MeshCentral 0.3.9-b, works fine in test enviroment.

**Comment by senolkehya** [comment]
Hi,
In 0.3.9-c windows workstations agents can connect.
All the server editions of windows agents can not connect.

**Comment by Ylianst** [comment]
This is bad. Bryan will take a look at it this morning.

**Comment by Ylianst** [comment]
I just published MeshCentral v0.3.9-d with the antivirus status removed until Bryan fixes it as I imagine that it the problem. If you can give that version a try and confirm it works for you, that would be great.

One more thing you can do is go in the agent console and type "av" like the image below. I suspect on some machines the agent will lockup, but I would like to confirm that is the problem.

Thanks in advance,
Ylian

![x](https://user-images.githubusercontent.com/1319013/62480132-e39eef00-b763-11e9-805c-2ce0b95ee4bc.png)

**Comment by TitovLab** [comment]
MeshCentral v0.3.9-d works on Windows Server 2012R2, service restarts sucessfully.
After run av in console - meshagent stuck, service restart failed - only process killing.
Thank you!

**Comment by Ylianst** [comment]
Bryan just looked at it and did the correct fix. Published MeshCentral v0.3.9-e that will display antivirus status on Windows versions that support it and correctly not hang on versions that do not. If this new version works, that should close this issue.

**Comment by PathfinderNetworks** [comment]
I just updated my server to 0.3.9-e.  Do we need to manually restart the MeshAgent service on the affected devices or will they automatically reconnect on their own after the update?

**Comment by southeasterntech** [comment]
On numerous 2016 servers, on 0.3.6-e , with a fresh install of the agent from the server running 0.3.6-e, the Server shows online, then after about 2 minutes...it switches to offline and never returns despite restarting the agent.  Thinking this issue is still not fixed.

**Comment by southeasterntech** [comment]
> On numerous 2016 servers, on 0.3.6-e , with a fresh install of the agent from the server running 0.3.6-e, the Server shows online, then after about 2 minutes...it switches to offline and never returns despite restarting the agent. Thinking this issue is still not fixed.

Actually, every one of our servers (probably 60 various Win servers) are now offline in MC..Linux seems not affected.  It's possible that those servers are running older versions of mesh unless they autoupdated.  But on 0.3.6-e, they're showing offline, even with the new agent

**Comment by krayon007** [comment]
Can you run it in console mode? from the command line run:

meshagent run

and it should show what it is doing.

Also, when you say you restarted the agent, do you mean from the service manager, or restarting the OS? I looked at the build script, and it looks like only the Debug Builds have the deadlock detection enabled, which means the version that was released with Mesh Central has it disabled, which means, the agent deadlocked, so it will not autoupdate, unless you either manually kill the agent process, or reboot the machine. This is probably why the agent shows as offline after 2 minutes, because the control channel has a 2 minute keep-alive interval.. 

I think if you try to install the agent on a machine that already has the agent installed that is deadlocked, I'm not sure if the install will actually succeed or not. But if the server is updated, when you reboot the client OS, it should auto-update correctly on first connect, becuase it will attempt to update before running any code. In the meantime, I'll update the build script, so both the Debug and Release versions has the deadlock detection enabled. Normally what was supposed to happen, is that the agent would've auto-restarted after 10 minutes if it was deadlocked, which would be when it would've auto-updated as well, if the server was updated.

**Comment by PathfinderNetworks** [comment]
I manually stopped and restarted the MeshAgent service on the servers I could still access (most of them, fortunately). So far they are all staying connected.  Some of them have been connected for almost an hour now.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.3.9-f with new MeshAgent with Windows deadlock detection. Thanks to Bryan for this. Now if the agent lock-up again like it did with the AV detection on Windows server, it will auto-exit after 10 minutes and the service manager will auto-started it. Linux will also get this in an upcoming update.

**Comment by TitovLab** [comment]
MeshCentral v0.3.9-h works fine on Windows Server 2019.
Thank you!

**Comment by southeasterntech** [comment]
I also can confirm that v0.3.9-h is working now

**Comment by krayon007** [comment]
I think I figured it out. Windows Server 2008 doesn't support Unicode hostnames, so a recent update where we added UTF8 support to support non English characters, broke windows server 2008, because some of those APIs are only supported in windows server 2012.

I'll update the code to dynamically link those APIs, so I can detect if they aren't supported, and fall back to ANSI. This should fix Windows Server 2008 R2
