### ISSUE TITLE
Mesh Agent log

### ISSUE THREAD

**Issue by IntExCZ** [Ylianst/MeshCentral#474]
Is there any log of connecting/running Mesh Agent Windows service?
I am using VPN software that breaks the agent connection to my Mesh Central server. Without the VPN everythings works good. I would like inspect the agent connection problems and solve the issue. My tip is on proxy server that is used when the VPN connection is made...

**Comment by krayon007** [comment]
Edit the .msh file and add the following line:

controlChannelDebug=1

This will log everything connection related. To turn it off change the line to:

controlChannelDebug=

**Comment by IntExCZ** [comment]
Thank you, it created log file with same output as console agent run by executing "MeshAget.exe run" which I have now discovered. 

It shows connection errors to server so I think that it cannot use proxy server.

There are some switches when issuing a help:
`PS C:\Program Files\Mesh Agent> .\MeshAgent.exe /?
Mesh Agent available switches:
  run               Start as a console agent.
  connect           Start as a temporary console agent.
  start             Start the service.
  restart           Restart the service.
  stop              Stop the service.
  state             Display the running state of the service.
  -signcheck        Perform self-check.
  -install          Install the service from this location.
  -uninstall        Remove the service from this location.
  -nodeidhex        Return the current agent identifier.
  -fullinstall      Copy agent into program files, install and launch.
  -fulluninstall    Stop agent and clean up the program files location.
  -proxy:host:port  Specifiy an HTTPS proxy (after -fullinstall only).
  -tag:xxx          Specifiy a agent tag  (after -fullinstall only).
  -resetnodeid      Reset the NodeID next time the service is started.`

But when I try to use "-proxy" switch it just tells the agent name and exits:
`PS C:\Program Files\Mesh Agent> .\MeshAgent.exe run -proxy:http://internet-proxy-s1.cz.o2:8080
MeshCentral2 Agent
PS C:\Program Files\Mesh Agent>` 

If I issue a "start" instead of "run", the agent starts normally as a service but without using the proxy settings so it still do not connect.

Is this a bug or am I using it wrong?

Thank you.

**Comment by krayon007** [comment]
That proxy switch might be a remnant of the console mode app, I'm not sure if it's hooked up correctly for the service, I'll look into it 

But anyways, is your issue that you need to use a proxy when you normally don't or vice versa? If so, if a system proxy is set, the agent should automatically try with the proxy, and then without the proxy if the connection fails.

If no proxy is set, and one is needed for the VPN case, then I can see how that can fail... If that's the case, I'll see if I can add a setting where you can bind proxy configurations with particular interfaces...

**Comment by IntExCZ** [comment]
Without VPN I can directly access any port on any server and agent connects to my Mesh Central server without problems.

But with VPN connected, only ports 80 and 443 are "proxyfied" so the agent cannot connect even if I can access my Mesh Central web administration using browser without problems. 

I think that problem is in the proxy usage, because the TortoiseSVN (for example) cannot connect on VPN without proxy settings either.

I need first to figure out, how to connect to Mesh Central through VPN over proxy. ;-)

Thank you :-)

**Comment by IntExCZ** [comment]
Just a note, the VPN simulates real company network settings when I am on site.

I have tried to run SSH on port 443 on my server and it connected without problems so there should not be any filtering when communication is encrypted.

**Comment by IntExCZ** [comment]
> That proxy switch might be a remnant of the console mode app, I'm not sure if it's hooked up correctly for the service, I'll look into it
> 
> But anyways, is your issue that you need to use a proxy when you normally don't or vice versa? If so, if a system proxy is set, the agent should automatically try with the proxy, and then without the proxy if the connection fails.
> 
> If no proxy is set, and one is needed for the VPN case, then I can see how that can fail... If that's the case, I'll see if I can add a setting where you can bind proxy configurations with particular interfaces...

Is there any progress with it? I would like to control my notebook behind proxy and as I have checked, the agent really cannot use it. :-(

**Comment by krayon007** [comment]
I implemented functionality to determine which interface the gateway is reachable on. I tested it with our corporate VPN, so I should be able to add support for per interface proxy settings, so that depending on if your VPN is connected, will determine wh a t proxy settings (if any) to use. This should be made available next week.

**Comment by IntExCZ** [comment]
Prefect, thank you! I hope that it will solve the problem. :-)
By the way, how are the proxy settings detected? Maybe setting the proxy manually on default interface would solve the problem too. ;-)

**Comment by MailYouLater** [comment]
@IntExCZ: I wonder, if you restart the Mesh Agent service after you're connected to the VPN, does it connect correctly? or does it still fail to connect until you disable the VPN?

**Comment by IntExCZ** [comment]
@MailYouLater It cannot connect with enabled VPN at all. I have tried to restart the service or run it manually with no luck. After deactivating VPN the agents connects successfully. It just can't use the VPN's proxy.

**Comment by JSuenram** [comment]
@IntExCZ 
Is the issue still present?
If solved, please close. 
Thank you!

**Comment by dinger1986** [comment]
old please close @si458 I think maybe a tidbit there about enabling logging in the agent which could be added to docs?

**Comment by si458** [comment]
the is already a section which has lots of information in but maybe need to add a little more
https://ylianst.github.io/MeshCentral/meshcentral/debugging/#meshagent
