### ISSUE TITLE
MongoDB Deprecation Warning

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentral#494]
-------- 9/20/2019, 11:05:41 AM ---- 0.4.0-y --------

(node:15017) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to MongoClient.connect.

**Comment by Ylianst** [comment]
What version of NodeJS and MongoDB are you using?

**Comment by hunter-nl** [comment]
NodeJS v12.10.0
MongoDB v4.0.12

**Comment by Ylianst** [comment]
Thanks. Added "useUnifiedTopology: true" to the MongoDB connection options. That should fix this in MeshCentral 0.4.1-a when it is released (probably latest today).

**Comment by Ylianst** [comment]
Published MeshCentral v0.4.1-a with this fix.

**Comment by Ylianst** [comment]
Can you confirm the new server does now show the "DeprecationWarning" anymore? Thanks.

**Comment by hunter-nl** [comment]
I try to upgrade through web UI and also through npm install meshcentral (in the past this always works).
The current version was v0.4.0-y after the steps above. It said it is v0.4.0-z now. In web ui I see v0.4.1-d is available, but it will not upgrade to this version. With v0.4.0-z the "deprecationWarning" still exist.

**Comment by Ylianst** [comment]
That is weird. You can update to an explicit version by doing this:

`npm install meshcentral@0.4.1-d`

**Comment by hunter-nl** [comment]
I tried that already. But then the database and configuration gets destroyed.

**Comment by Ylianst** [comment]
Hi. So, first the new agents are in version "0.4.1-a" and above. So, you should not have changed agents so far. i also don't understand why an update would reset the server configuration. The "node_modules" folder does not contain any configuration. You can rename the "node_modules" folder, do "npm install meshcentral" to create a new "node_modules" and run the server. The state of the server is kept in MongoDB and/or "meshcentral-data" and "meshcentral-files".

**Comment by hunter-nl** [comment]
I've removed de node_modules folder. And run rpm install meshcentral.
This installed 0.4.0-z. Only after forcing the explicit version 0.4.1-h I could update this from 0.4.0-z fresh installed version to 0.4.1-h. Installing directly to 0.4.1-h is not possible for unknown reason. So why npm repository thinks 0.4.0-z is the latest version?

In 0.4.1-h the mongodb warning message is gone now. So this issue is solved. Only the npm repository is not OK.

**Comment by Ylianst** [comment]
To query NPM for the latest version of MeshCentral, I use the following command:

`npm view meshcentral dist-tags.latest`

You can try this manually and see what you get back.

**Comment by hunter-nl** [comment]
I did a complete new fresh install. It is working again and mongo warning does not exist anymore.
