### ISSUE TITLE
Last seen time is off by hours

### ISSUE THREAD

**Issue by PathfinderNetworks** [Ylianst/MeshCentral#531]
Not sure if this has been brought up yet or not- but I'm noticing that the device 'Last Seen' time is off.  It doesn't seem to always be the same amount time that it is off (but can't be certain yet).  Right now I'm looking at a device that shows the last seen time as being 10:40:46pm but, if I look at the events list, it shows I disconnected from that device at 11:17:05pm (at which time I rebooted the device).  The 11:17pm time is the correct one. 
I know the issue with the 7 Day Power State timeline always showing the device as being connected (even if it's not) has been discussed- but I can't recall if the Last Seen time indication being incorrect was part of that?

**Comment by Ylianst** [comment]
Thanks for the report. I happen to be at work now (9pm Saturday) to fix a problem with the user consent dialog box I introduced yesterday and saw this. I just looked at it and indeed, due to lines of code being in the wrong order, I was saving the last time the device connected, not the time it was disconnected. I fixed it, it's in MeshCentral v0.4.1-v now. Let me know if that works. :)

**Comment by PathfinderNetworks** [comment]
I just updated to 0.4.1-v and will keep an eye on it.  I will have to wait for a device to be shut down to know for sure.  Thanks!

**Comment by PathfinderNetworks** [comment]
It still doesn't appear to be working correctly. But, this time, I think it's just that the Last Seen time shown in the device view isn't taking in to consideration the GMT time offset.  For example, the device I'm currently looking at shows the Last Seen time as 12:58:55am on 10/6/19.  But if I download the powerevents.csv I can see the actual last connect time was 00:58:55 GMT -0400 10/6/19 (so 8:58pm EST on 10/6/19).

**Comment by Ylianst** [comment]
Ha! Thanks for the report. I will look into this. Your probably exactly right as to what the problem is. I think there is another problem where if a device disconnects, the real time data for the last connection will not be updated correctly. I want to look into this too. If you hit refresh you will see the right value.

**Comment by Ylianst** [comment]
I took a look at the server time and it looks ok. Can you check & confirm that your server is set to the correct time and timezone? Of course, if the server clock is not set, it would be a problem.

**Comment by PathfinderNetworks** [comment]
That was the first thing I took a look at to be honest.  I'm looking at a bunch of devices tonight.  It now looks like the Last Seen time is just showing the last entry in the powerevents.csv log.  Not the time it was actually turned off.  When I look at the powerevents.csv file there is a 1 and 0 for the state- I assume a 1 represents when the device made contact and a 0 is when it was disconnected?  If so, then it actually looks as though it's not logging when the device was turned off.  For example, I'm looking at a device that was turned off today around 5pm. But the last entry in the powerevents.csv file is the time the device was turned on this morning (or at least that's what it appears to be to me).  This employee does come in to work each day around that time.  That 7;33;22 time is what is displayed in the Last Seen: time in the device view. 
![powerevents](https://user-images.githubusercontent.com/48607498/66530870-9a5a7b00-ead7-11e9-89d0-4d9d8dd2a915.JPG)

**Comment by dinger1986** [comment]
sounds like a #wontfix @si458
