### ISSUE TITLE
actual count and displayed count of device group and device

### ISSUE THREAD

**Issue by Tech-Werkz** [Ylianst/MeshCentral#7198]
**Describe the bug**
I'm trying to check the actual count of the device group and actual device count on every user group and i found out the it is not tally to the actual count versus the displayed count.
I guess its because of the previous devices/groups being deleted due to duplicates

**To Reproduce**
manual count the device group and devices on every user group

**Expected behavior**
 it should be the actual count of the device added 

**Server Software (please complete the following information):**
 Windows 10 
latest version MeshCentral
MySQL DB

**Client Device (please complete the following information):**
 Windows 10 /11/ server 2012
lates agent

**Remote Device (please complete the following information):**
 Local server

current config
WAN Only with Reverse proxy

**Comment by si458** [comment]
you are going to show screenshots as i dont follow what you mean?

**Comment by Tech-Werkz** [comment]
sorry,  i'll send sample screenshot

**Comment by Tech-Werkz** [comment]
![Image](https://github.com/user-attachments/assets/8e088d21-0798-4dc7-9a7d-18849fb2c0e7)

**Comment by Tech-Werkz** [comment]
13 in manual count but above its counted as 18 devices

**Comment by si458** [comment]
have you tried different web browser and machines? (you dont say u have or even what browsers you have tested)
also developer mode now...
open up devtools in web browser
type `usergroups` into the `console` tab and you should get a JSON value out
right click the json output and click `copy object`
visit https://jsoneditoronline.org, paste the output into their,
switch to tree view, then browse the object and look for your groups id in question,
then expand it and count the number of `links` (the web ui might show `props` as a counter to help you 👍)

EDIT: you can also type `currentUserGroup` in the `console` tab of the dev tools and it will show the current group info
so copy this also info the jsoneditoronline and check how many are there also

**Comment by Tech-Werkz** [comment]
tried on edge,chrome,brave btowsers
same output devices 18 but (13 actual count)

tried on devtools (chrome)
usergroups : 20 props
when i expand it, it includes the 2 user and the 18 nodes

tried currentusergroup but says reference error

**Comment by si458** [comment]
sorry `currentUserGroup` is only visible when on the usergroup page in question (also case sensitive capital U and G)

but still, huh, so the must be something not right with your database then possibly, a mix up maybe?
i just cant seem t replicate the problem here

IF your free tomorrow, i can connect into your server with u (however you want) and we can look at it together
just give us a fleemail/whats/tele/discord/etc 👍

**Comment by Tech-Werkz** [comment]
my first encounter to this issue is on the device groups, and to fix it up(tempo solution)
i query the nodes and check the actual count on db, found out that 1 of the device group still exist in db nodes even if i already deleted it before, then i just deleted it to equalize the actual device group versus the displayed  total device group on my server

later on  i checked the user groups and found the same issue if misscounting device
my big suspect for this is the duplicating devices( some of the devices on user group) have history of duplicates before (already been fixed by skipmaccheck=1) and the duplicates was already been deleted
i readded the device again on user group that i created and i figured out that the device counts  just adds up from its former count

i hope my explanations is good 😅

**Comment by si458** [comment]
i think it does make sense but also very confusing because IF you had used the NeDB (the default db) i could understand
as it simply marks the entry as deleted BUT DOESNT ACTUALLY DELETE IT until later on OR on restart!
but with mysql/mongo/postgres/etc, they get DELETED straight away?
so the shouldnt be any hanging things.

only thing i can suggest at the moment, is try to replicate it

1. create group, 2. add users, 3. add devices, 4. did this, 5. did that, 6. this happened, 7. fixed by doing this, 8. and so on

then i can try have a look here whats going on why its not deleteing nodes etc from the links 
as it will be the `links` thats the issue

**Comment by Tech-Werkz** [comment]
yes it should be straightly deleted after deletion of device but on actual after checking on mysql db its still exist

**Comment by Tech-Werkz** [comment]
i tried to replicate it again with this procedure  @si458 : 

Create user group (test user group)
add device (test device)
add user

stop agent services
delete db file and msh file

download agent installer and install
a new device will show with the same name (test device) 1 online & 1 offline

select and delete offline device
go to user group created (test user group)
you will see that device has been removed on the list but devices count above still exist (1)

tried reboot server services
check count again on test user group(still count (1))

tried reboot server
check count again on test user group(still count (1))

**Comment by si458** [comment]
@Tech-Werkz brilliant thank you!!! replicated it exactly as you said
now to work out whats happening
im guessing when the device is deleted, its not removing links from the usergroup correctly

EDIT: yep correct, its not removing the links correctly (i had 1 device and 1 user for testing)

<img width="870" height="495" alt="Image" src="https://github.com/user-attachments/assets/bd53564a-c4ea-41cc-967d-f074fa828a06" />

**Comment by Tech-Werkz** [comment]
its also possible the same to device groups when deleted which can be checked on my server tab device groups count

**Comment by si458** [comment]
ok i figured it out, took some time (4 hours), commit is here to fix it https://github.com/Ylianst/MeshCentral/commit/5c5bcb415211b2c25ab9db6eb98d671301181d34
so you will need to patch your server and test for me plz or wait til next release or use master docker image when its ready

basically when you remove a device from the web ui, it was removing the links for users, but not usergroups!
it was also the same for the removeInactiveDevices, only user links were removed not usergroups!

i have no idea why but the code just wasnt in there at all?

also im not sure where else might have this problem, but those are the 2 places ive found, so if you find more do let me know!

ive also added an event log too so you know it was removed etc too

**Comment by Tech-Werkz** [comment]
thank you very much for your patience @si458 
I'll try to patch this tommorow if i can do, and feedback to you as soon as possible thanks !

**Comment by Tech-Werkz** [comment]
Thank you very much sir @si458 , the patch was successful and already tested the way ireplicate the issue before and its already ok
the count changing after delete and add. also tried on delete device group.
for now I'll just cleanup the excess nodes from the db to make it tally again on actual count then good to go !.. kuddos to you sir !

**Comment by si458** [comment]
@Tech-Werkz glad it worked! if you happen to spot the same issue with other things and user groups, do let me know!
