### ISSUE TITLE
Mobile Website Desktop page partially broken with Modern UI

### ISSUE THREAD

**Issue by jesta192** [Ylianst/MeshCentral#7318]
**Describe the bug**
When using the amazing new Modern UI mode, the mobile website doesn't present the mobile version of the Desktop connection page as demonstrated by Ylian in the YouTube video (https://youtu.be/-ND1H0Z750s?t=321). Instead, it appears to present the full page version as seen in Chrome on my laptop, and this makes usage difficult (it does not show the toolbar on the right with the mobile controls when I use the full-screen diagonal-arrows button, and I cannot pan the remote view; also the interface is truncated). I am not even able to see the remote desktop until I rotate my phone to landscape, after which the UI is incredibly cramped. However if I switch to Classic UI mode, I am able to access the version of the page Ylian showed, and the features seem to work as expected.

Notice also that the tabs for each node are long the top of the screen rather than the bottom, further indicating the mobile version of the pages are not being served when using Modern UI.

**To Reproduce**
1. Switch to Modern in the User Interface selection window.
2. Open a node, and use the Desktop tab to connect to the device.
3. Notice the UI is not the mobile interface but resembles the desktop interface.
4. Click the 4-way diagonal arrows to go full-screen.
5. Notice the desktop UI buttons are shown along the top and bottom and the interaction does not behave correctly.

**Expected behavior**
The UI behavior and controls should behave the same in both Modern and Classic UI modes.

**Screenshots**
<img width="236" height="449" alt="Image" src="https://github.com/user-attachments/assets/6f22f4f6-4a79-4417-a93c-ffec82611134" />&nbsp;<img width="237" height="449" alt="Image" src="https://github.com/user-attachments/assets/176b4542-d017-4dd0-ad9a-a9ab65c21e81" />

<img width="2561" height="909" alt="Image" src="https://github.com/user-attachments/assets/1b189e8e-778e-4369-a105-2d3d8e5bbff6" />

**Server Software (please complete the following information):**
 - OS: Raspbian (Debian GNU/Linux 11 (bullseye))
 - Virtualization: Docker Compose
 - Network: LAN/WAN with NGINX proxy server
 - Version: 1.1.51 (also 1.1.50)
 - Node: 22.16.0 (official MeshCentral Docker image from ghcr.io/ylianst/meshcentral:latest)

**Client Device (please complete the following information):**
 - Device: Samsung Galaxy S23 Ultra
 - OS: One UI 7 (based on Android 15)
 - Network: Remote over WAN
 - Browser: Google Chrome

**Remote Device (please complete the following information):**
Same as server

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "settings": {
    "plugins":{"enabled": false},
    "_mongoDb": null,
    "cert": "REDACTED",
    "_WANonly": true,
    "_LANonly": true,
    "sessionKey": "REDACTED",
    "port": 443,
    "aliasPort": 443,
    "redirPort": 80,
    "redirAliasPort": 80,
    "AgentPong": 300,
    "BrowserPong": 300,
    "TLSOffload": true,
    "SelfUpdate": false,
    "AllowFraming": false,
    "WebRTC": false
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "minify": true,
      "mobileSite": true,
      "NewAccounts": false,
      "_userNameIsEmail": true,
      "certUrl": "REDACTED",
      "allowedOrigin": [ "REDACTED", "raspberrypi.local" ],
      "agentInviteCodes": true,
      "localSessionRecording": true,
      "sessionRecording": {
        "_onlySelectedUsers": true,
        "_onlySelectedUserGroups": true,
        "onlySelectedDeviceGroups": true,
        "_filepath": "C:\\temp",
        "index": true,
        "_maxRecordings": 10,
        "_maxRecordingDays": 15,
        "maxRecordingSizeMegabytes": 10000,
        "__protocols__": "Is an array: 1 = Terminal, 2 = Desktop, 5 = Files, 100 = Intel AMT WSMAN, 101 = Intel AMT Redirection, 200 = Messenger",
        "_protocols": [ 1, 2, 101 ],
        "protocols": [ 1, 2 ]
      }
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
    "email": "REDACTED",
    "names": "REDACTED",
    "production": true
  },
  "smtp": {
    "host": "REDACTED",
    "port": 465,
    "from": "REDACTED",
    "auth": {
      "clientId": "REDACTED",
      "clientSecret": "REDACTED",
      "refreshToken": "REDACTED"
    },
    "user": "REDACTED",
    "emailDelaySeconds": 10,
    "tls": true,
    "verifyEmail": true
  }
}
```

**Comment by si458** [comment]
This is by design...

You have asked ur user to use the new modern ui on the desktop, so its going to load up the new modern ui on ur mobile phone

The way around this is to add `?mobile=1` to the url and it will force the old style mobile version

We are aware of a few bugs with the new modern ui and mobile devices, still trying to iron those out

**Comment by jesta192** [comment]
> This is by design...
> 
> You have asked ur user to use the new modern ui on the desktop, so its going to load up the new modern ui on ur mobile phone
> 
> The way around this is to add `?mobile=1` to the url and it will force the old style mobile version
> 
> We are aware of a few bugs with the new modern ui and mobile devices, still trying to iron those out

Thx. I have seen that the Modern UI seems to be designed to be responsive and used on both desktop and mobile browsers. It seems to work pretty well overall, but the Classic UI for the Desktop tab is definitely much easier to use.

Perhaps if the option to switch to Modern UI vs Classic did not apply per-user, but instead applied to each browser by way of cookies or something like that, it would be easier to work around. Right now if I want to use Modern UI on my laptop, I have to use it on my phone as well, unless I switch it there. Which means now my laptop is using Classic mode as well. It's a small thing but could get tedious. One other thing about this is I can't find a way to switch back to Modern UI on mobile from the Classic UI (the diamond button doesn't seem to show up at all in Classic UI on mobile 🤔)

**Comment by jesta192** [comment]
> The way around this is to add `?mobile=1` to the url and it will force the old style mobile version

By the way, this doesn't seem to actually work for me. It still gives me the Modern UI with this parameter...

**Comment by si458** [comment]
@jesta192 sadly the styling is done BEFORE the page is rendered,
 and which style you use (`sitestyle`) is stored in your users webstatesession in the database so as you move around devices its follows you

sadly we didnt implement an option on the mobile ui to switch from the old ui to the modern ui
if you need this then please open a feature request and we can look into adding it for the next release for you!

as for `?mobile=1` not working, try using `?sitestyle=2` as this forces the classic ui so should trigger the mobile ui

**Comment by jesta192** [comment]
> as for `?mobile=1` not working, try using `?sitestyle=2` as this forces the classic ui so should trigger the mobile ui

Yes this does take me to the Classic UI with the mobile interface. It does not seem to keep this if I "install" the page as an app on Android (using the "Add to Home screen" option in the Chrome menu, which is unfortunate. It's probably a limitation of Chrome in that regard though. If I turn on Airplane Mode as suggested by a Reddit thread, I can create a shortcut to the MC page instead of "installing" it and it will keep the mobile interface, but it doesn't treat it as a standalone app anymore.

**Comment by si458** [comment]
@The-Dev-Ryan just wondered if your fixes you are doing currently will fix this issue at all?

**Comment by The-Dev-Ryan** [comment]
> [@The-Dev-Ryan](https://github.com/The-Dev-Ryan) just wondered if your fixes you are doing currently will fix this issue at all?

Hey mate, the current fixes don't include this but I will add it to the list to look into :)

**Comment by si458** [comment]
@The-Dev-Ryan sure no worries! Can be another pr done another day! No rush!

**Comment by si458** [comment]
has this been resolved in the latest release at all 1.1.54?

**Comment by jesta192** [comment]
> has this been resolved in the latest release at all 1.1.54?

Thanks for continuing to work on this.

In a quick update and test, v1.1.54 doesn't seem to have made any difference for me. I have my shortcut url including `?viewmode=2&sitestyle=2` which gives me the older UI, and the Desktop tab works as expected. Removing those url parameters brings me back to the Modern UI, and it seems to still have issues displaying the Desktop connection (blank remote screen when in portrait mode after entering full-screen but it shows up in landscape; no controls overlay for interacting with the remote system at the top-right of the display; truncated/cut-off controls at the top of the screen).

**Comment by The-Dev-Ryan** [comment]
> has this been resolved in the latest release at all 1.1.54?

Hey sorry mate not had a chance to look into this more yet.

**Comment by my1770** [comment]
Hi. Nothing has changed in version 1.5.6. Just add it ?viewmode=2&sitestyle=2. Have you found a solution?
